name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  migrate-staging-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Run Prisma Migrations on Staging DB
        run: pnpm prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.STAGING_DIRECT_URL }}

      - name: Run Data Migration Scripts
        run: |
          for script in prisma/migrations/migrate-*.ts; do
            if [ -f "$script" ]; then
              echo "Running migration script: $script"
              npx tsx "$script"
            fi
          done
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
          DIRECT_URL: ${{ secrets.STAGING_DIRECT_URL }}

      - name: Verify Staging Database Schema
        run: pnpm prisma migrate status --schema=./prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.STAGING_DIRECT_URL }}

      - name: Check for Drift in Staging
        run: |
          DRIFT=$(pnpm prisma migrate diff --from-schema-datasource ./prisma/schema.prisma --to-url $DIRECT_URL --exit-code || echo "drift")
          if [ "$DRIFT" = "drift" ]; then
            echo "❌ Drift detected in Staging DB!"
            exit 1
          else
            echo "✅ No drift in Staging DB."
          fi
        env:
          DIRECT_URL: ${{ secrets.STAGING_DIRECT_URL }}

  migrate-production-db:
    runs-on: ubuntu-latest
    needs: migrate-staging-db

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Run Prisma Migrations on Production DB
        run: pnpm prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DIRECT_URL }}

      - name: Run Data Migration Scripts
        run: |
          for script in prisma/migrations/migrate-*.ts; do
            if [ -f "$script" ]; then
              echo "Running migration script: $script"
              npx tsx "$script"
            fi
          done
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DIRECT_URL }}

      - name: Verify Production Database Schema
        run: pnpm prisma migrate status --schema=./prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DIRECT_URL }}

      - name: Check for Drift in Production
        run: |
          DRIFT=$(pnpm prisma migrate diff --from-schema-datasource ./prisma/schema.prisma --to-url $DIRECT_URL --exit-code || echo "drift")
          if [ "$DRIFT" = "drift" ]; then
            echo "❌ Drift detected in Production DB!"
            exit 1
          else
            echo "✅ No drift in Production DB."
          fi
        env:
          DIRECT_URL: ${{ secrets.PRODUCTION_DIRECT_URL }}
